### ISSUE TITLE
store partition scheme on recovery partiton

### ISSUE THREAD

**Issue by cabillman** [pennmanor/pmage#9]
Currently we are relying on filesystem labels to determine which root filesystem to apply the image too. While this approach works it is problematic when the imager doesn't complete because the label could be missing. The next time pmage is started it won't be able to determine what partition to use because the label is missing.

One fix could be storing the filesystem partition  + default labels in a txt file on the recovery partition. If pmage is not able to determine the partitions from the current labels it could fall back to using that txt file as defaults.

Another potentially more robust option (although more invasive since it impacts FLDT) would be to use GPT partition labels. Currently FLDT images with MSDOS partition tables.

**Comment by tomswartz07** [comment]
I'm open to modifying what we need with the FLDT update to transition to GPT partitions.
Especially since it will greatly simplfy this issue.

**Comment by cabillman** [comment]
sfdisk equivalent for gpt partitons

http://askubuntu.com/questions/57908/how-can-i-quickly-copy-a-gpt-partition-scheme-from-one-hard-drive-to-another

**Comment by tomswartz07** [comment]
Looking into this with Buildroot to update the PXE image.
I've made great progress so far, the updated kernel helps quite a bit.
Buildroot, however, will not allow for `sgdisk`, I'm looking at using `parted` to do the same thing.

Once I tweak the buildroot config, I'll toss it up into it's own repo.

**Comment by cabillman** [comment]
I came across this when looking up partitioning options. It has a nice clean api if you end up needing to script things. It is used by red hat's installer so i'm sure it is well supported.

http://blivet.readthedocs.org/en/latest/intro.html

I've never used it and using parted directly might be a better option. Just passing the info along :)

**Comment by tomswartz07** [comment]
I'm tracking the `parted` additions within my fork of FLDT.
Once the `deployImage` scripts are updated with the proper parted formatting, we can roll on with GPT and then assign static partition names.

Status can be followed [here](https://github.com/tomswartz07/FLDT/issues/7).

Do you have a preference for the naming scheme; keeping `root_a`and `root_b`?

**Comment by cabillman** [comment]
The name doesn't really matter. I have it hard coded to root_a and root_b right now but it is something I wanted to make configurable anyway.

**Comment by tomswartz07** [comment]
I have the latest updates to FLDT up; with support for GPT schemes.
The only major change is that we need to re-create a `partitions.txt` file, but I've made it so that it's a bit easier to generate.

I'll follow up with more info as I get the rest of the recent changes documented.

**Comment by cabillman** [comment]
The partition label code has been committed and appears to be working.
